version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: vue-i18n
    versions:
    - 9.1.2
    - 9.1.3
    - 9.1.4
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: "@vue/test-utils"
    versions:
    - 1.1.2
